<x-core-setting::section
    :title="trans('plugins/2fa::2fa.settings.title')"
    :description="trans('plugins/2fa::2fa.settings.description')"
>
    <x-core-setting::on-off
        name="2fa_enabled"
        :label="trans('plugins/2fa::2fa.settings.enable_global')"
        :value="\ArchiElite\TwoFactorAuthentication\TwoFactor::isSettingEnabled()"
    />
</x-core-setting::section>
